### ISSUE TITLE
Could not read configuration

### ISSUE THREAD

**Issue by AaronDavidSchneider** [bordaigorl/remy#1]
Thanks for your awesome tool! I am looking forward to get it working on my remarkable.

When I start remygui.py I still get the following message:
```
Started
Could not read configuration from '/Users/schneider/Library/Preferences/remy.json'!
```

I installed all the dependencies and created the config json in `/Users/schneider/Library/Preferences/remy.json` with the following content:

```json
{
  "sources": {
      "source1": {
  	"name": "reMarkable (RSync)",
  	"type": "rsync",
  	"data_dir": "/Users/schneider/Documents/remarkable/remy",
  	"address": "192.168.178.16",
  	"host": "remarkable",
  	"key": "~/.ssh/id_rsa",
  	"username": "root",
  	"timeout": 3,
  	"use_banner": "remy-banner.png"
	}
  },
  "default_source": "source1",
}
```

What am I doing wrong?
Thanks!

**Comment by bordaigorl** [comment]
The trailing comma after `"default_source": "source1",`!
I know this is annoying, but it's a limitation of the strict parsing of Python's `json` module.
It does not parse trailing commas nor C-like comments.
If you want to test your configuration, try and run `import json; json.load('YOURPATH')` and see if it complains.
(also note: you are free to choose whatever id for the source, does not need to be "sourceN")

**Comment by AaronDavidSchneider** [comment]
Solved
