### ISSUE TITLE
suggestion: server sync

### ISSUE THREAD

**Issue by benneti** [bordaigorl/remy#13]
I have a system service on my remarkable setup (using systemds path watching) to push new files to my server whenever I change something, to be able to use these It would be necessary to set the remote_roots folder, are you open to me implementing a setting for this?

**Comment by bordaigorl** [comment]
If I understand correctly you would like to be able to change from the config file, the value of `remote_roots` in the live file sources, correct?
I don't see any disadvantage in doing so (but I am not sure I understand the advantage either!)

**Comment by benneti** [comment]
The advantage would be, that on the tablet I can create a systemd service:
`/etc/systemd/system/documents.path`
```
[Path]
PathChanged=/home/root/.local/share/remarkable/xochitl
Unit=documents.service

[Install]
WantedBy=default.target
```
with the service file
```
[Unit]
Description=Syncs remarkable documents to remote

[Service]
ExecStart=/opt/bin/rsync -rauvhP ~/.local/share/remarkable/xochitl/ --delete user@remote:~/remarkable/documents
```
and analogous for the templates.
When I now setup remy with this folder I do not need to care that the remarkable is unlocked and or in the wifi which is comfortable in my opinion.

I am also thinking about the most comfortable way to implement pulling but I did not come to a conclusion for that, I think an additional folder from which I pull periodically from the remarkable and delete pulled files would be the best.

**Comment by benneti** [comment]
This is now possible on remys end
