### ISSUE TITLE
Feedback (WSL 2 Ubuntu 20.04)

### ISSUE THREAD

**Issue by DeepMarks** [bordaigorl/remy#17]
Thanks for this wonderful application, works like a charm!

As requested here is some feedback:

1. Exporting documents works fine, however it doesn't seem to support epub/ebooks. I guess that's intended?

2. Importing files doesn't work at all on my system. The info panel simply rejects the upload of PDFs.

3. No matter where I put remy-banner.png it doesn't recognize it. Tried to adapt the config.json file but had no sucess so far. Any advice?

Looking forward to your response and already stoked for new features.

Thanks again!

**Comment by bordaigorl** [comment]
> * Exporting documents works fine, however it doesn't seem to support epub/ebooks. I guess that's intended?

Yes, but it's just because I don't use them.
I think that internally they are converted to pdf, so it could be just a matter of hooking the export functions to the right files.
Initially I thought I would have had to reimplement an HTML renderer to render the epub from Remy, and so I just decided I was not going to support it.
I would certainly help if anybody wanted to contribute this feature.

> * Importing files doesn't work at all on my system. The info panel simply rejects the upload of PDFs.

This is weird. I may have misunderstood the drag&drop API.
As a workaround I am going to add a context menu so you don't need to rely on the drag&drop.

> * No matter where I put remy-banner.png it doesn't recognize it. Tried to adapt the config.json file but had no sucess so far. Any advice?

Have you installed `remarkable-splash` on the tablet?
If so, try with an absolute path in `use_banner`.

**Comment by DeepMarks** [comment]
> Yes, but it's just because I don't use them.
> I think that internally they are converted to pdf, so it could be just a matter of hooking the export functions to the right files.
> Initially I thought I would have had to reimplement an HTML renderer to render the epub from Remy, and so I just decided I was not going to support it.
> I would certainly help if anybody wanted to contribute this feature.

Yeah I thought that was probably the case, I don't use them much either but might look into it.

> This is weird. I may have misunderstood the drag&drop API.
> As a workaround I am going to add a context menu so you don't need to rely on the drag&drop.

That would be great, thanks!

> Have you installed `remarkable-splash` on the tablet?
> If so, try with an absolute path in `use_banner`.

It seems I have overlooked the necessity of installing remarkable-splash. Any chance you could give me a short instruction how to install it on RM2 without breaking it? I don't seem to find one on the page itself.

**Comment by bordaigorl** [comment]
> Any chance you could give me a short instruction how to install it on RM2 without breaking it?

Ah I just realised `remarkable-splash` will probably not work on RM2...

**Comment by bordaigorl** [comment]
> Importing files doesn't work at all on my system. The info panel simply rejects the upload of PDFs.

A question about this: when you say "rejects" do you mean that the panel shows the dashed landing zone for the drag&drop but when you drop nothing happens, or is it that the panel does not react to drag&drop at all?
Note that the import function is only enabled for "live" sources, which means it is disabled if you are loading a local backup.

**Comment by DeepMarks** [comment]
> Ah I just realised `remarkable-splash` will probably not work on RM2...

Oh I see, well it's not that important as long as the application itself is working fine

**Comment by DeepMarks** [comment]
> A question about this: when you say "rejects" do you mean that the panel shows the dashed landing zone for the drag&drop but when you drop nothing happens, or is it that the panel does not react to drag&drop at all?
> Note that the import function is only enabled for "live" sources, which means it is disabled if you are loading a local backup.

The panel doesn't react at all if I drag&drop a pdf stored on my computer, I'm connected to the RM via USB-SSH so I guess it should be working or am I missing something?

**Comment by bordaigorl** [comment]
The "landing zone" is the empty space below the title/details. Would help to see a video of the interaction

**Comment by DeepMarks** [comment]
That's what it looks like for me, might be due to my WSL setup...

https://user-images.githubusercontent.com/44670190/111500285-1da7e380-8744-11eb-8b00-8c61aef0529f.mp4

**Comment by DeepMarks** [comment]
Additionally, I just noticed that the RSync source takes longer to startup than usb, I thought it should be the other way around since RSync is only syncing a part of the files?

**Comment by DeepMarks** [comment]
The context menu works great, thanks for adding it.
