### ISSUE TITLE
EPUB import

### ISSUE THREAD

**Issue by akutuzov** [bordaigorl/remy#22]
Thanks for your work!

Is it impossible to import EPUB files to reMarkable using remy?
When I try to import a EPUB, it is then shown as a PDF in remy, and of course reMarkable cannot read it.

**Comment by bordaigorl** [comment]
Hi! Have you tried the [`devel`](https://github.com/bordaigorl/remy/tree/devel) branch?
I added full EPUB support there. The only caveat is that immediately after upload, if you open it the preview would look blank. You need to open the file on the remarkable once, then Remy would pick it up and you can preview/export it correctly.
(I am planning to display some warning boxes)

**Comment by akutuzov** [comment]
Thanks!
With the `devel` branch, attempts to upload a *.epub file result in
```
Traceback (most recent call last):
  File "remy/gui/browser/__init__.py", line 436, in uploadIntoCurrentEntry
    self._requestUpload(entry.uid, [], filenames)
  File "remy/gui/browser/__init__.py", line 362, in _requestUpload
    opt = QApplication.instance().config.get("upload")
  File "remy/remarkable/config.py", line 142, in get
    raise RemyConfigException("Option '%s' not found in configuration." % opt)
remy.remarkable.config.RemyConfigException: Option 'upload' not found in configuration.
```

**Comment by bordaigorl** [comment]
Ah that's annoying! There are some new configurations that should be optional but they were expected to be there.
The latest commit 2305dd78f69d6828fe923577ec4cfa11fd3bd3f3 should solve this. Could you test it again?

**Comment by akutuzov** [comment]
Yes, now this works, thanks!

In fact, the `devel` version seems to be quite robust and much more functional than `master`. Any plans to merge?

**Comment by bordaigorl** [comment]
Yes I was planning to merge it but I wanted more feedback from testers (like you! Thanks!).
At the moment I'm very busy so it may take a while, but it will be eventually merged with a new release issued.
