### ISSUE TITLE
Private ssh key considered as invalid

### ISSUE THREAD

**Issue by tbrandysky** [bordaigorl/remy#27]
I'm using a ssh key to log in to my Remarkable 2.
It seems remy has problems with this fully working ssh key which I am using daily:

![Screenshot from 2022-02-18 14-44-12](https://user-images.githubusercontent.com/3275770/154694504-a1f009fb-eb8d-4ba4-ac49-78ce6b2ff3df.png)

my private key:
$ file /home/shamot/.ssh/id_rsa-Thinkpad
/home/shamot/.ssh/id_rsa-Thinkpad: OpenSSH private key

configuration part:
...
13         "source2": {
 14           "name": "reMarkable (WiFi)",
 15           "type": "ssh",
 16           "host": "192.168.0.40",
 17           "key": "/home/shamot/.ssh/id_rsa-Thinkpad",                                                                                                                                                                                     
 18           "username": "root",
 19           "timeout": 3,
 20           "use_banner": "remy-banner.png"
 21           }
...

**Comment by bordaigorl** [comment]
Could be an instance of this:
https://stackoverflow.com/questions/54612609/paramiko-not-a-valid-rsa-private-key-file

**Comment by tbrandysky** [comment]
this could be, I can test it later. Could you consider supporting this private key standard? I've created this ssh key using the ssh-keygen command which is pretty common and considered as standard on Linux.
