### ISSUE TITLE
'upload' options block missing from reference config, crash if it's absent

### ISSUE THREAD

**Issue by fancypantalons** [bordaigorl/remy#29]
It looks like the recent merge of the 'devel' branch added a new mandatory 'upload' configuration block.  Without it, I found uploading documents via ssh caused a crash ala:

```
Traceback (most recent call last):                                                        
  File "/home/brettk/git/remy/remy/gui/browser/__init__.py", line 376, in _requestUpload  
    opt = QApplication.instance().config.upload                                           
  File "/home/brettk/git/remy/remy/remarkable/config.py", line 178, in upload
    return self.renderOptionsFrom('upload')                                               
  File "/home/brettk/git/remy/remy/remarkable/config.py", line 155, in renderOptionsFrom  
    opt = deepcopy(self.get(key))                                                         
  File "/home/brettk/git/remy/remy/remarkable/config.py", line 151, in get                
    raise RemyConfigException("Option '%s' not found in configuration." % opt)            
```

I can't find any reference document around this and the `example_config.json` doesn't include this block.

I was able to fix it by adding this JSON block to my configuration, and while it's sufficient to get it to work, it's unclear to me if everything in it is necessary:

```json
    "upload": {                                                                           
        "default_options": {}                                                             
    }    
```

I'm happy to throw together a PR to correct these issues if I got some raw material for the settings that could go in the block and how they're used.  I suspect I could also throw in some better error handling in the case where the block is absent.

**Comment by bordaigorl** [comment]
Ah that was silly! It was previously called `import` and I forgot to rename it in the config defaults!
Thanks for the feedback.
