### ISSUE TITLE
Better antialiasing for pencil

### ISSUE THREAD

**Issue by stevenbell** [bordaigorl/remy#3]
I'm in the habit of using the mechanical pencil for most of my notes.  When I look at a page I've written, the combination of the Qt `Dense3Pattern` and my display resolution lead to some really horrible aliasing in the preview window.

Adding the lines below to the `PageGraphicsItem` setup helped a lot, but there was still a bit of aliasing.

    self.setRenderHint(QPainter.Antialiasing);
    self.setRenderHint(QPainter.SmoothPixmapTransform);

Maybe there are other flags to set?  It's been a long time since I've used Qt, so I'm just shooting in the dark at the moment.

**Comment by bordaigorl** [comment]
Using `Dense3Pattern` is really just a temporary hack.
The rendering on the tablet is beautiful, very nuanced, very dynamic and a pain to reverse-engineer.
I almost never use pencil so I don't have an incentive to try and do much better than what I have now.
I wanted to include a basic "pencil" texture (i.e. random noise of different densities) but that would not really replicate the tablet's pencil.

My guess for doing properly would be to:
- draw the strokes using the coordinate/pressure data
- produce the outline of such strokes using `QPainterPathStroker`
- use that outline as a clip path
- blit pencil texture varying density according to data within the clipped path

PRs welcome 😉

**Comment by stevenbell** [comment]
Hmm, I wasn't going to go quite that far... I was just hoping to squash the aliasing issues in the preview.

It looks like [Qt just does bilinear interpolation](https://doc.qt.io/qt-5/qt.html#TransformationMode-enum) to scale pixmaps.  This is fine when scaling up or down to 1/2 scale, but below that things start to fall apart.  For example, in the screenshot below, there's a weird pale band running diagonally across the text.

![Screenshot from 2020-07-28 18-06-59](https://user-images.githubusercontent.com/1936591/88727875-816e9500-d0fe-11ea-88d4-3a7d6db4fde7.png)

The same effect is visible with dot backgrounds, although it's generally not a big deal.

I'll have to do some more experiments with Qt to figure out what the options are.  Unfortunately that's probably not going to happen for a few weeks.

**Comment by bordaigorl** [comment]
Argh that does not look great (I seem to get different artifacts on my machine).
Is there a better fallback that would work for you?
What if we just rendered it with solid lines? The dotted pattern is not that great anyway.
Another option is to alter opacity as a poor-man way to reproduce the effect of going over the same strokes many times...

**Comment by bordaigorl** [comment]
I pushed a new version with proper pencil rendering, it should render much better now!
