### ISSUE TITLE
Include a requirements.txt file

### ISSUE THREAD

**Issue by SJWyatt** [bordaigorl/remy#34]
Firstly, this is a really useful app, thank you!

However I had a few issues installing dependencies the first time because of PyPDF2 just released a new version with breaking changes (version 2.0.0)

Specifically they removed the PyPDF.pdf module. (See [here](https://github.com/py-pdf/PyPDF2/releases/tag/2.0.0))
This causes the following error:
```
Traceback (most recent call last):
  File "<github directory>/remygui.py", line 1, in <module>
    from remy.gui import app                               
  File "<github directory>/remy/gui/app.py", line 19, in <module>
    from remy.gui.notebookview import *
  File "<github directory>/remy/gui/notebookview/__init__.py", line 11, in <module>
    from remy.gui.notebookview.view import *
  File "<github directory>/remy/gui/notebookview/view.py", line 11, in <module>
    from remy.gui.export import exportDocument
  File "<github directory>/gui/export/__init__.py", line 8, in <module>
    from remy.remarkable.export import Exporter, CancelledExporter
  File "<github directory>/remy/remarkable/export.py", line 9, in <module>
    from PyPDF2.pdf import PageObject
ModuleNotFoundError: No module named 'PyPDF2.pdf'
```

With this in mind it would be really useful to include a requirements.txt with the latest supported dependencies so new users installing this for the first time can just run `pip3 install -r requirements.txt` and be done! This makes sure that only the compatible versions of the libraries are installed.

(For anyone coming across the same problem, installing with `pip3 install PyPDF2==1.28.4` fixed this issue for me.)

**Comment by zerone01y** [comment]
I actually have issues with pyPDF2=1.28.4. They changed the function `mergeRotatedScaledTranslatedPage` in 1.28, which breaks the function to export annotated pdfs. 

Now I install pyPDF2=1.27 and no problem so far. 

I hope @bordaigorl could do something like `conda env export` (sorry I don't know much about pip), so we can ensure the environment is correctly configured.
