### ISSUE TITLE
Highlights NOT transparent

### ISSUE THREAD

**Issue by hbendi** [bordaigorl/remy#40]
### Expected

Text visible under text

| ![pkb dev bup - dPaper backup script _2_0611_2022-09-18_T16-52-02](https://user-images.githubusercontent.com/23709548/190910539-3324850c-43db-4542-8423-14b91c5b2e24.png) |
|:--:|
| **remy Preview mode. Highlights transparent.** |

| ![pkb dev bup - dPaper backup script _2_0612_2022-09-18_T16-52-10](https://user-images.githubusercontent.com/23709548/190910536-5ec24990-ec53-4309-93f3-53a835801f3b.png) |
|:--:|
| **remy Preview mode. Export settings.** |

### Actual

Highlights overlap/foreground as solid colours. Lines/Text under highlight NOT visible.

| ![pkb dev bup - dPaper backup script _2_0613_2022-09-18_T16-54-53](https://user-images.githubusercontent.com/23709548/190910541-48ca1ad0-276c-428c-aef8-c807eaf8691d.png) |
|:--:|
| **remy exported version. View on Adobe Reader.** |

**Comment by bordaigorl** [comment]
Thanks for the report!
This looks strange. The highlighting is handled a bit specially because the PDF generation backend does not understand blend modes (which are the way the tabled uses for highlights after the highlights update) and so it needs to fall back to using opacity. Have you perhaps customised the colors in the configuration file?

**Comment by hbendi** [comment]
CLI shows some errors for highlight strokes.
I changed the [default colour](https://github.com/bordaigorl/remy/blob/0d162bdd3d4844cf69796c78ce3f8b169ca6dd5f/remy/remarkable/render.py#L265) for unknown pen tools (from red to yellow), but no avail.

|![pkb dev bup - dPaper backup script _2_0284_2022-09-17_T14-43-41_sw prob - remy reMarkable manager recognize highlight tool #fails_upl](https://user-images.githubusercontent.com/23709548/191744705-9b95ae59-fd6b-492f-98bb-8be3917b1968.png)|
|--|
|**Error - highlight tool NOT recognized.**|

**Comment by bordaigorl** [comment]
Ah thanks that explains it.
I never saw color 0 for highlighters in my tests.
I am happy to add it; what color were you using on the tablet? What color do you see from the tablet's export? Is this from a long time ago or after the update that introduced the new highligters?

**Comment by hbendi** [comment]
> What color do you see from the tablet's export? 

My tablet storage is full.

### Problem

reMarkable cloud duplicated and shuffled pages in my notebooks, starting with new policies regarding Cloud Connect. Now tablet storage is full. Hence, I cannot delete anything on tablet to free storage. Official method would be to factory reset. I prefer to keep my notebooks.

Thus,

1. create new notebooks #fails.
2. open quick sheets #fails.
3. open existing notebook #works, show penstrokes #works, create penstrokes #works, but save new penstrokes #fails.

### Workaround

0. User data files (including notebooks) already copied to PC local storage.
1. delete files from tablet with CLI manually.
2. open new notebook
3. write/scribble with highlight tool
4. reconnect tablet to PC
5. copy noteobok files
6. check code used for highlight
7. change code for ALL other files (loop regex match over all files that should contain highlight info)

> Is this from a long time ago or after the update that introduced the new highligters?

Long time ago, i.e. before the breaking/highlight update. Opening tablet, there is 'Exported colour' option. Indeed, there is no red, only yellow, green, pink and gray. 

Would like to default 0 to green or gray if possible.

**Comment by bordaigorl** [comment]
> Would like to default 0 to green or gray if possible.

I just pushed a (1 line!) fix to this problem. Now color 0 is recognised as the legacy highlighter.
It will be rendered as semi-transparent yellow by default, but you can change the color using the `highlighter` color key in the settings (or clicking on the first highlighter color in the palette options of the export dialog).

Regarding your issues with the full tablet:
there would be a way to resolve your issues.
If you know which pages are duplicates you can edit the metadata on the tablet so they get discarded and then remove the files associated with them.
For help on how to do that you can ask in the [Discord server](https://discord.gg/u3P9sDW).

**Comment by hbendi** [comment]
Thank you for your patience, guidance and help.

Will check the Discord channel.
