### ISSUE TITLE
"Updated" sorts alphabetically

### ISSUE THREAD

**Issue by gimmy** [bordaigorl/remy#48]
The "Updated" column does not sort things properly, as it seems that the sorting is alphabetical. 
![update](https://user-images.githubusercontent.com/1421027/201620657-07a29ea1-b517-4845-87fb-c58f7aa6f786.png)

**Comment by bordaigorl** [comment]
Should be addressed in 98d19e71fb9b0c00c30fe5e87a90b2aaa4967373

**Comment by gimmy** [comment]
Thanks! Also ebc5d97 is very nice. :+1:
