### ISSUE TITLE
No image file upload?

### ISSUE THREAD

**Issue by cesss** [bordaigorl/remy#53]
I thought the rM2 supported viewing JPGs and PNGs. I just tried uploading a JPG, nothing was uploaded, and checking the terminal found this error: "remy.remarkable.metadata.RemarkableError: Can only upload PDF and EPUB files, but was given a .JPG"

**Comment by RedTartan04** [comment]
No, rM desktop app and also IIRC USB web interface wont upload image files. Not sure about 3rd party apps.

**Comment by bordaigorl** [comment]
I thought of supporting this, but the only way to implement it would be to convert the image to pdf first, which does not seem to be the thing you are expecting. This is a limitation of the current firmware of the tablet, nothing Remy can solve.

**Comment by cesss** [comment]
Oh, I thought their official software could be using for viewing images! Don't worry then! Yes, I did exactly that, convert my images to PDF and upload them that way. Don't invest time in implementing that in Remy, better implement the 3.x lines format when it's fully reverse engineered (which I'm not sure because I'm not following the advances lately... anyway I won't update my rM2 to 3.x until most apps from the community supports it.
